### ISSUE TITLE
Totally lost

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [firestuff/architype#17]
I can make two nodes. How do I draw a link between them? What's a group? 

The documentation focuses right now on each command in isolation. It might be clearer to add some tutorials that say "suppose you want to draw this diagram" and show you how to do it.

**Comment by flamingcow66** [comment]
Added tutorial, example diagram, and link from the help page. Feel free to reopen with additional suggestions, and thanks for the report!
